config/routes.rb
Rails.application.routes.draw do

  resources :walls
  get 'pages/home'

  devise_for :users
  devise_scope :user do 
    authenticated :user do
      root to: "pages#home", as: :authenticated_root, via: :get
    end
    unauthenticated do
      root to:"devise/sessions#new"
    end
  end
  

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ActiveRecord::Base

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
   has_many :wall_memberships
    has_many :walls, through: :wall_memberships
end

app/models/wall.rb
class Wall < ActiveRecord::Base
    has_many :wall_memberships
    has_many :users, through: :wall_memberships
end

app/models/wall_membership.rb
class WallMembership < ActiveRecord::Base
  belongs_to :wall
  belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
def home
end

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.fetch(:user, {})
    end
end

app/controllers/walls_controller.rb
class WallsController < ApplicationController
  before_action :set_wall, only: [:show, :edit, :update, :destroy]

  # GET /walls
  # GET /walls.json
  def index
    @walls = Wall.all
  end

  # GET /walls/1
  # GET /walls/1.json
  def show
  end

  # GET /walls/new
  def new
    @wall = Wall.new
  end

  # GET /walls/1/edit
  def edit
  end

  # POST /walls
  # POST /walls.json
  def create
    @wall = Wall.new(wall_params)

    respond_to do |format|
      if @wall.save
        format.html { redirect_to @wall, notice: 'Wall was successfully created.' }
        format.json { render :show, status: :created, location: @wall }
      else
        format.html { render :new }
        format.json { render json: @wall.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /walls/1
  # PATCH/PUT /walls/1.json
  def update
    respond_to do |format|
      if @wall.update(wall_params)
        format.html { redirect_to @wall, notice: 'Wall was successfully updated.' }
        format.json { render :show, status: :ok, location: @wall }
      else
        format.html { render :edit }
        format.json { render json: @wall.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /walls/1
  # DELETE /walls/1.json
  def destroy
    @wall.destroy
    respond_to do |format|
      format.html { redirect_to walls_url, notice: 'Wall was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_wall
      @wall = Wall.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def wall_params
      params.require(:wall).permit(:title, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/walls_helper.rb
module WallsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>

  <p class="navbar-text pull-right">
<% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
<% else %>
  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
<% end %>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  
  <% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>

<%= yield %>

</body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/users/_form.html.erb
<<<<<<< HEAD
<%= form_for(user) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
=======
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
>>>>>>> 53b05b41225b0054217f818205c7bfa2b6d3b5e4
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<<<<<<< HEAD
<%= render 'form', user: @user %>
=======
<%= render 'form' %>
>>>>>>> 53b05b41225b0054217f818205c7bfa2b6d3b5e4

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/home.html.erb
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>Hello world from Cloud9!</title>
<<<<<<< HEAD
        <link type="text/css" rel="stylesheet" href="homepage.css"/>
        <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">

<!-- Latest compiled and minified JavaScript -->
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>
    </head>
    
    <body>
        <h1>WALLS</h1>
        
      

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
        
        
        <div class="container">
          <div class="jumbotron">
            <div id="myCarousel" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
    <li data-target="#myCarousel" data-slide-to="1"></li>
    <li data-target="#myCarousel" data-slide-to="2"></li>
    <li data-target="#myCarousel" data-slide-to="3"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
    <div class="item active">
      <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/6/68/Gay_flag.svg/2000px-Gay_flag.svg.png" alt="">
      <div class="carousel-caption"> 
      <p>LGBTQ+</p>
      </div>
    </div>

    <div class="item">
      <img src="http://polishedcreatives.com/wp-content/uploads/2015/07/BlackLivesMatter-1.jpg" alt="">
    </div>

    <div class="item">
      <img src="http://mediad.publicbroadcasting.net/p/wnpr/files/styles/x_large/public/201411/10697342_835688053119856_7676551658706407223_o.jpg" alt="">
    </div>

    <div class="item">
      <img src="http://media1.s-nbcnews.com/j/newscms/2016_09/1440106/160301-refugees-calais-terrorists-mdl-904_a417a7420770175b4dc9239cfd90e096.nbcnews-ux-2880-1000.jpg" alt="">
    </div>
  </div>

  <!-- Left and right controls -->
  <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
        </div>
        
        <div class="row">
              <div class="col-md-3">.col-md-4</div>
              <div class="col-md-3">.col-md-4</div>
              <div class="col-md-3">.col-md-4</div>
              <div class="col-md-3">.col-md-4</div>
        </div>
        
        
        <div class="container">
    <div class="row">
        <div class="span6 offset3">
            <form>
                <input class="input-xxlarge" type="text" placeholder="Email..">
                <p style="line-height: 70px; text-align: center;"><button type="submit" class="btn btn-primary">Sign Up</button></p>
            </form>
        </div>
    </div>
</div>
        
    

=======
               
    <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">
<link type="text/css" rel="stylesheet" href="home.css">
<!-- Latest compiled and minified JavaScript -->
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>
    </head>
    <body>
        </head>
	
	<body style="background-color: green;">
		<h1 style="font-size: 40px;text-align:center; font-color: Blue"><strong>Express, Express! Equality!!</strong></h1>
<button>Regular Button</button>
<button class="btn btn-primary">Primary Button</button>
<button class="btn btn-info">Info Button</button>
<button class="btn btn-success">Success Button</button>
<button class="btn btn-warning">Issues Button</button>
<button class="btn btn-danger">Forum Button</button>
    <div class="row">
			<ol style="background-color: yellow;">
				<li>African American</li>	
				<li>LGBTQ</li>
				<li>Latinos</li>
			</ol>	
			<h2 style="color: blue; font-size: 20px; font-family:Arial">  What to do?</h1>

             <p1>    This website is a great website that involves freedom of expression in which one can express feelings and interests about a certain field of social injustice
   outlined below.</p1> 
             <p2>   One can also get resources such as prmiary sources, links and connections to nearby or statewide organizationsconnect to your topic. The topic is shown in the table. You do not have to pick the topic for your resources, but for the wall, or forum, you make 
   you will have to get a set topic.</p2>
       <p1 style="text-aligned: center"></p1>
   
    <table border="4px">
            <tr>
                <td>Racial Issues</td>
                <td>LGBTQ</td>
                <td>African Americans</td>
                <td>Latinas</td>
            </tr>
 </div>
     <a href="https://ide.c9.io/unsurmountable22/awesomeproject"></a>
         
     <a href="http://www.bing.com/videos/search?q=LGBTQ+in+Massachusetts&=&view=detail&mid=4E1CDC0DA9FE073F58C74E1CDC0DA9FE073F58C7&FORM=VDHSOP&fsscr=0">Current Issues</a>
      <embed="http://www.bing.com/videos/search?q=LGBTQ+in+Massachusetts&=&view=detail&mid=4E1CDC0DA9FE073F58C74E1CDC0DA9FE073F58C7&FORM=VDHSOP&fsscr=0">Current issues</embed>  
>>>>>>> 53b05b41225b0054217f818205c7bfa2b6d3b5e4
    </body>
</html>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<<<<<<< HEAD
<h1>Users</h1>

<table>
=======
<h1>Listing Users</h1>

<table>,
>>>>>>> 53b05b41225b0054217f818205c7bfa2b6d3b5e4
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<<<<<<< HEAD
<%= render 'form', user: @user %>
=======
<%= render 'form' %>
>>>>>>> 53b05b41225b0054217f818205c7bfa2b6d3b5e4

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

app/views/walls/_form.html.erb
<%= form_for(@wall) do |f| %>
  <% if @wall.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@wall.errors.count, "error") %> prohibited this wall from being saved:</h2>

      <ul>
      <% @wall.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/walls/edit.html.erb
<h1>Editing Wall</h1>

<%= render 'form' %>

<%= link_to 'Show', @wall %> |
<%= link_to 'Back', walls_path %>

app/views/walls/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Walls</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @walls.each do |wall| %>
      <tr>
        <td><%= wall.title %></td>
        <td><%= wall.description %></td>
        <td><%= link_to 'Show', wall %></td>
        <td><%= link_to 'Edit', edit_wall_path(wall) %></td>
        <td><%= link_to 'Destroy', wall, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Wall', new_wall_path %>

app/views/walls/new.html.erb
<h1>New Wall</h1>

<%= render 'form' %>

<%= link_to 'Back', walls_path %>

app/views/walls/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @wall.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @wall.description %>
</p>

<%= link_to 'Edit', edit_wall_path(@wall) %> |
<%= link_to 'Back', walls_path %>